import * as T from '../vendor/three.module.js';
import {createRollCharacter} from './roll-character.js';
const $=id=>document.getElementById(id);
const canvas=$('world');
let renderer;
try { renderer=new T.WebGLRenderer({canvas,antialias:true,powerPreference:'high-performance'}); }
catch(e){$('fallback').hidden=false;throw e;}
renderer.setPixelRatio(Math.min(devicePixelRatio,1.6));renderer.setSize(innerWidth,innerHeight);renderer.shadowMap.enabled=true;renderer.shadowMap.type=T.PCFSoftShadowMap;renderer.outputColorSpace=T.SRGBColorSpace;renderer.toneMapping=T.ACESFilmicToneMapping;renderer.toneMappingExposure=1.2;
const scene=new T.Scene();scene.background=new T.Color('#261637');scene.fog=new T.FogExp2('#422542',.012);
const camera=new T.PerspectiveCamera(54,innerWidth/innerHeight,.1,220);
scene.add(new T.HemisphereLight('#a8e9ff','#a32d1b',2.5));
const sun=new T.DirectionalLight('#ffe4bd',3.8);sun.position.set(-22,40,18);sun.castShadow=true;sun.shadow.mapSize.set(1024,1024);Object.assign(sun.shadow.camera,{left:-40,right:40,top:40,bottom:-40,near:1,far:110});sun.shadow.bias=-.001;scene.add(sun);
const rim=new T.DirectionalLight('#66cfff',2);rim.position.set(30,15,-25);scene.add(rim);
const materials=new Map();
function mat(color,emissive=false){const key=color+emissive;if(!materials.has(key))materials.set(key,new T.MeshStandardMaterial({color,roughness:.6,metalness:.08,emissive:emissive?color:'#000',emissiveIntensity:emissive?.7:0}));return materials.get(key);}
function mesh(g,c,x=0,y=0,z=0,parent=scene,glow=false){const o=new T.Mesh(g,mat(c,glow));o.position.set(x,y,z);o.castShadow=true;o.receiveShadow=true;parent.add(o);return o;}
function box(w,h,d,c,x,y,z,parent=scene){return mesh(new T.BoxGeometry(w,h,d),c,x,y,z,parent);}
function ball(r,c,x,y,z,parent=scene){return mesh(new T.SphereGeometry(r,12,8),c,x,y,z,parent);}
function bar(a,b,r,c,parent=scene){const start=new T.Vector3(...a),end=new T.Vector3(...b),v=end.clone().sub(start);const o=mesh(new T.CylinderGeometry(r,r,v.length(),6),c,...start.clone().add(end).multiplyScalar(.5).toArray(),parent);o.quaternion.setFromUnitVectors(new T.Vector3(0,1,0),v.normalize());return o;}
let seed=1759;const rand=()=>{seed=(seed*1664525+1013904223)>>>0;return seed/4294967296;};
const ground=box(66,2,66,'#b63c29',0,-1,0);const groundTex=new T.TextureLoader().load('/images/cube/city-ground.webp');groundTex.wrapS=groundTex.wrapT=T.RepeatWrapping;groundTex.repeat.set(6,6);groundTex.colorSpace=T.SRGBColorSpace;ground.material=new T.MeshStandardMaterial({map:groundTex,color:'#f39878',roughness:.95});
const route=[[-25,26],[-25,15],[-12,15],[-12,4],[7,4],[7,-8],[-9,-8],[-9,-20],[18,-20],[24,-27]];
const lengths=route.slice(1).map((p,i)=>Math.hypot(p[0]-route[i][0],p[1]-route[i][1]));const total=lengths.reduce((a,b)=>a+b,0);
function along(distance){let d=distance;for(let i=0;i<lengths.length;i++){if(d<=lengths[i]){const t=d/lengths[i];return new T.Vector3(T.MathUtils.lerp(route[i][0],route[i+1][0],t),0,T.MathUtils.lerp(route[i][1],route[i+1][1],t));}d-=lengths[i];}return new T.Vector3(route.at(-1)[0],0,route.at(-1)[1]);}
function pathDistance(x,z){let best=Infinity;for(let i=0;i<lengths.length;i++){const a=route[i],b=route[i+1],vx=b[0]-a[0],vz=b[1]-a[1],t=T.MathUtils.clamp(((x-a[0])*vx+(z-a[1])*vz)/(vx*vx+vz*vz),0,1);best=Math.min(best,Math.hypot(x-a[0]-t*vx,z-a[1]-t*vz));}return best;}
for(let i=0;i<lengths.length;i++){const a=route[i],b=route[i+1],p=box(4,.07,lengths[i]+3,'#dbb363',(a[0]+b[0])/2,.04,(a[1]+b[1])/2);p.rotation.y=Math.atan2(b[0]-a[0],b[1]-a[1]);}
const trail=[];for(let d=0;d<total;d+=2.7){const p=along(d);const o=mesh(new T.TorusGeometry(.16,.045,6,12),'#71f9ff',p.x,.15,p.z,scene,true);o.rotation.x=Math.PI/2;trail.push(o);}
// Windows are a shared texture, so the toy buildings stay light on phones.
const wc=document.createElement('canvas');wc.width=wc.height=128;const wx=wc.getContext('2d');wx.fillStyle='#fff4df';wx.fillRect(0,0,128,128);for(let y=8;y<128;y+=24)for(let x=8;x<128;x+=24){wx.fillStyle=(x+y)%48?'#304370':'#c68d54';wx.fillRect(x,y,12,15);}const windowTex=new T.CanvasTexture(wc);windowTex.colorSpace=T.SRGBColorSpace;
const collisions=[];const palette=['#ef713b','#e7b458','#47b8c4','#9e6ad5','#f18faa','#85bce7','#a7bc67'];
for(let i=0;i<75;i++){const x=rand()*58-29,z=rand()*58-29;if(pathDistance(x,z)<5 || (z<-22&&x>16))continue;const w=1.5+rand()*1.8,d=1.5+rand()*1.6,h=2+rand()*7,c=palette[i%palette.length];const b=box(w,h,d,c,x,h/2,z);b.material=new T.MeshStandardMaterial({map:windowTex,color:c,roughness:.65});collisions.push({x,z,w:w/2+.42,d:d/2+.42,h});if(h<4){mesh(new T.ConeGeometry(w*.8,1.15,4),'#8044aa',x,h+.52,z).rotation.y=Math.PI/4;}else{box(w*.72,.4,d*.72,c,x,h+.2,z);if(i%3===0)bar([x,h,z],[x,h+1.4,z],.035,'#e5dcaf');}}
for(let i=0;i<45;i++){const x=rand()*62-31,z=rand()*62-31;if(pathDistance(x,z)<3.3)continue;const h=.8+rand()*.6;bar([x,0,z],[x,h,z],.14,'#76452b');ball(.7+rand()*.3,['#65a338','#2f9b56','#ed9a32'][i%3],x,h+.45,z);}
// Recognizable miniature landmarks share the playable world, not a backdrop.
function eiffel(x,z){const g=new T.Group();g.position.set(x,0,z);scene.add(g);for(const sx of [-1,1])for(const sz of [-1,1]){bar([sx*2,0,sz*2],[sx*.6,6,sz*.6],.14,'#d9a569',g);bar([sx*.6,6,sz*.6],[0,11,0],.09,'#d9a569',g);}for(let y=1;y<9;y+=1.2){const k=2*(1-y/11);for(const zsign of [-1,1])bar([-k,y,zsign*k],[k,y,zsign*k],.09,'#b68152',g);for(const xsign of [-1,1])bar([xsign*k,y,-k],[xsign*k,y,k],.09,'#b68152',g);}box(2,.3,2,'#ba8e63',0,5,0,g);bar([0,10,0],[0,12,0],.05,'#ffdf9f',g);}
eiffel(-18,-1);
const liberty=new T.Group();liberty.position.set(0,0,-15);scene.add(liberty);box(2.5,1.8,2.5,'#c18d66',0,.9,0,liberty);mesh(new T.ConeGeometry(1.2,4.6,8),'#56bca0',0,4,0,liberty);ball(.6,'#56bca0',0,6.7,0,liberty);for(let i=0;i<7;i++){const a=i/7*Math.PI*2;bar([Math.sin(a)*.4,7.1,Math.cos(a)*.4],[Math.sin(a)*.9,7.6,Math.cos(a)*.9],.08,'#56bca0',liberty);}bar([-.6,5.6,0],[-1.6,8.3,0],.2,'#56bca0',liberty);mesh(new T.ConeGeometry(.3,.9,8),'#ffd13e',-1.6,8.8,0,liberty,true);box(.7,1,.3,'#63a593',.85,5.2,.2,liberty);
const ferris=new T.Group();ferris.position.set(16,5,-6);scene.add(ferris);const wheel=mesh(new T.TorusGeometry(3.4,.15,8,40),'#ffb145',0,0,0,ferris);for(let i=0;i<12;i++){const a=i/12*Math.PI*2;bar([0,0,0],[Math.cos(a)*3.4,Math.sin(a)*3.4,0],.055,'#ffe292',ferris);box(.7,.65,.7,palette[i%7],Math.cos(a)*3.4,Math.sin(a)*3.4,0,ferris);}bar([16,0,-7],[16,5,-6],.2,'#c49d7a');bar([16,0,-5],[16,5,-6],.2,'#c49d7a');
const wind=new T.Group();wind.position.set(-19,4,-23);scene.add(wind);mesh(new T.ConeGeometry(1.6,5,8),'#c4895e',-19,2.5,-23);for(let i=0;i<4;i++){const a=i*Math.PI/2;const blade=box(.6,3,.12,'#ffc784',Math.sin(a)*1.5,Math.cos(a)*1.5,.1,wind);blade.rotation.z=-a;}ball(.25,'#784323',0,0,.2,wind);
const rocket=new T.Group();rocket.position.set(24,0,-27);scene.add(rocket);mesh(new T.CylinderGeometry(.85,1.15,5.5,16),'#fff1dd',0,3.3,0,rocket);mesh(new T.ConeGeometry(.86,1.8,16),'#283145',0,6.9,0,rocket);for(let i=0;i<3;i++){const a=i/3*Math.PI*2;box(.35,2,1.9,'#ee5e56',Math.sin(a)*1.1,1,Math.cos(a)*1.1,rocket).rotation.y=a;}ball(.5,'#74d9ed',0,4.8,1,rocket);const flame=mesh(new T.ConeGeometry(.75,2,12),'#ffb34c',0,.1,0,rocket,true);flame.rotation.x=Math.PI;
const sofa=new T.Group();sofa.position.set(-30,0,19);scene.add(sofa);box(3.5,.7,1.5,'#d92e41',0,.65,0,sofa);box(3.5,1.3,.4,'#ef4152',0,1.2,-.65,sofa);box(.4,.8,1.5,'#ef4152',-1.7,1,0,sofa);box(.4,.8,1.5,'#ef4152',1.7,1,0,sofa);
for(let i=0;i<9;i++){const x=-28+i*6,z=i%2?11:-25;if(pathDistance(x,z)<3)continue;box(1.9,.8,1,'#e84553',x,.55,z);box(1,.6,.9,'#72c8db',x,1.1,z);for(const sx of [-.6,.6])for(const sz of [-.52,.52]){const o=mesh(new T.CylinderGeometry(.28,.28,.16,10),'#202439',x+sx,.35,z+sz);o.rotation.x=Math.PI/2;}}
const ship=new T.Group();ship.position.set(26,0,8);scene.add(ship);mesh(new T.CylinderGeometry(1,1.4,6,4),'#24334c',0,1,0,ship).rotation.z=Math.PI/2;box(5,1,2,'#fff2de',0,2,0,ship);for(let i=0;i<6;i++)ball(.12,'#274465',-2.2+i*.8,2.1,1.03,ship);box(3,.8,1.4,'#fff2de',0,2.9,0,ship);bar([0,2.8,0],[0,4.5,0],.06,'#eed1a7',ship);
const plane=new T.Group();scene.add(plane);const body=mesh(new T.CylinderGeometry(.18,.4,3.8,10),'#fff3e1',0,0,0,plane);body.rotation.z=Math.PI/2;box(1.1,.1,4.8,'#8aaadd',0,0,0,plane);box(.5,.7,1,'#728ed0',-1.5,.3,0,plane);
// Scenic AI city silhouettes sit beyond the playable streets; no collision walls.
const texLoader=new T.TextureLoader();for(let i=0;i<4;i++){const texture=texLoader.load('/images/cube/city-'+['front','right','back','left'][i]+'.webp');texture.colorSpace=T.SRGBColorSpace;const mural=new T.Mesh(new T.PlaneGeometry(47,35),new T.MeshBasicMaterial({map:texture,transparent:true,alphaTest:.08,side:T.DoubleSide,depthWrite:false}));const a=i*Math.PI/2;mural.position.set(Math.sin(a)*43,14,Math.cos(a)*43);mural.rotation.y=a+Math.PI;scene.add(mural);}
const planet=mesh(new T.SphereGeometry(19,32,24),'#e85333',35,25,-80);planet.castShadow=false;
const starPositions=new Float32Array(600*3);for(let i=0;i<600;i++){starPositions[i*3]=(rand()-.5)*190;starPositions[i*3+1]=20+rand()*80;starPositions[i*3+2]=(rand()-.5)*190;}const stars=new T.BufferGeometry();stars.setAttribute('position',new T.BufferAttribute(starPositions,3));scene.add(new T.Points(stars,new T.PointsMaterial({color:'#a9dfff',size:.14,transparent:true,opacity:.8})));
// The same rabbit robot and pilot used by Furious Roll.
const player=new T.Group();player.position.set(-25,0,26);scene.add(player);
const rollCharacter=createRollCharacter();rollCharacter.group.rotation.y=Math.PI;rollCharacter.group.scale.setScalar(1.22);player.add(rollCharacter.group);

const shadow=mesh(new T.CircleGeometry(.65,24),'#321b2d',-25,.085,26);shadow.rotation.x=-Math.PI/2;shadow.material=new T.MeshBasicMaterial({color:'#291726',transparent:true,opacity:.28,depthWrite:false});
const pickups=[];for(let i=0;i<12;i++){const position=along(5+i*(total-10)/12);const item=mesh(new T.OctahedronGeometry(.32),'#84fbff',position.x,1.1,position.z,scene,true);pickups.push({item,position,taken:false});}
const obstacles=[];for(const d of [23,54,86]){const p=along(d);const o=box(2.8,.7,1,'#ae5f34',p.x,.35,p.z);obstacles.push({x:p.x,z:p.z,w:1.7,d:.8,h:.7});o.material=new T.MeshStandardMaterial({color:'#d99a58',roughness:.7});}
const checkpoints=[new T.Vector3(-25,0,26),new T.Vector3(-12,0,4),new T.Vector3(7,0,-8),new T.Vector3(-9,0,-20)];
const checkpointRings=checkpoints.slice(1).map(p=>{const ring=mesh(new T.TorusGeometry(1.3,.08,8,32),'#ffdc73',p.x,1.6,p.z,scene,true);return ring;});
const keys=new Set();let yaw=0,velocityY=0,grounded=true,checkpoint=0,collected=0,energy=T.MathUtils.clamp(Number(new URLSearchParams(location.search).get('light'))||100,25,100),paused=false,ended=false,jumpQueued=false,clickTarget=null,elapsed=0;
function jump(){if(grounded&&!paused&&!ended){velocityY=7.4;grounded=false;}}
function clearInput(){keys.clear();clickTarget=null;document.querySelectorAll('.held').forEach(b=>b.classList.remove('held'));}
window.addEventListener('keydown',e=>{if(['ArrowUp','ArrowDown','ArrowLeft','ArrowRight','Space','KeyW','KeyA','KeyS','KeyD'].includes(e.code)){e.preventDefault();keys.add(e.code);clickTarget=null;if(e.code==='Space'&&!e.repeat)jumpQueued=true;}if(e.code==='Escape')togglePause();});window.addEventListener('keyup',e=>keys.delete(e.code));window.addEventListener('blur',clearInput);document.addEventListener('visibilitychange',()=>{clearInput();last=0;});
for(const button of document.querySelectorAll('[data-key]')){button.addEventListener('pointerdown',e=>{e.preventDefault();button.setPointerCapture(e.pointerId);button.classList.add('held');keys.add(button.dataset.key);clickTarget=null;if(button.dataset.key==='Space')jumpQueued=true;});const up=()=>{keys.delete(button.dataset.key);button.classList.remove('held');};button.addEventListener('pointerup',up);button.addEventListener('pointercancel',up);button.addEventListener('lostpointercapture',up);}
let pointer=null;const ray=new T.Raycaster(),ndc=new T.Vector2();canvas.addEventListener('pointerdown',e=>{pointer={id:e.pointerId,x:e.clientX,y:e.clientY,startX:e.clientX,startY:e.clientY,moved:false};canvas.setPointerCapture(e.pointerId);});canvas.addEventListener('pointermove',e=>{if(!pointer||e.pointerId!==pointer.id)return;const dx=e.clientX-pointer.x;if(Math.hypot(e.clientX-pointer.startX,e.clientY-pointer.startY)>7)pointer.moved=true;if(pointer.moved)yaw-=dx*.006;pointer.x=e.clientX;pointer.y=e.clientY;});canvas.addEventListener('pointerup',e=>{if(!pointer||e.pointerId!==pointer.id)return;if(!pointer.moved&&!paused&&!ended){ndc.set(e.clientX/innerWidth*2-1,1-e.clientY/innerHeight*2);ray.setFromCamera(ndc,camera);const hit=ray.intersectObject(ground)[0];if(hit)clickTarget=hit.point.clone();}pointer=null;});canvas.addEventListener('pointercancel',()=>pointer=null);
function togglePause(){if(ended)return;paused=!paused;clearInput();$('pause').textContent=paused?'Resume':'Pause';$('pause').setAttribute('aria-pressed',String(paused));$('guide').textContent=paused?'Paused. Take your time.':'Move: WASD / arrows · Jump: Space · Tap the street to walk';}
$('pause').addEventListener('click',togglePause);
function respawn(){player.position.copy(checkpoints[checkpoint]);velocityY=0;grounded=true;energy=Math.max(energy,35);clickTarget=null;flash('Back at your checkpoint. Keep moving.');}
let guideUntil=0;function flash(text){$('guide').textContent=text;guideUntil=elapsed+5;}
function finish(won){ended=true;clearInput();$('overlay').hidden=false;$('result-title').textContent=won?'You lit up the city.':'The city dimmed.';$('result-copy').textContent=won?`${collected} sparks collected. The rocket is ready. Next stop: the gravity experiment.`:'Your checkpoint is safe. Restore the light and keep going.';$('retry').textContent=won?'Run again':'Continue from checkpoint';$('retry').focus();}
$('retry').addEventListener('click',()=>{if(collected>=8&&player.position.distanceTo(rocket.position)<3.2){checkpoint=collected=0;pickups.forEach(p=>{p.taken=false;p.item.visible=true;});}energy=100;ended=false;paused=false;$('overlay').hidden=true;respawn();canvas.focus();});
function blocked(x,z){for(const b of [...collisions,...obstacles])if(Math.abs(x-b.x)<b.w&&Math.abs(z-b.z)<b.d&&player.position.y<b.h-.05)return true;return false;}
function resize(){camera.aspect=innerWidth/innerHeight;camera.updateProjectionMatrix();renderer.setSize(innerWidth,innerHeight);}addEventListener('resize',resize);
let last=0;const target=new T.Vector3(),desired=new T.Vector3();camera.position.set(-25,9,38);camera.lookAt(-25,1,26);
function frame(now){requestAnimationFrame(frame);const dt=Math.min(last?(now-last)/1000:0,.04);last=now;if(document.hidden)return;
if(!paused&&!ended){elapsed+=dt;energy=Math.max(0,energy-dt*.38);if(jumpQueued){jump();jumpQueued=false;}let dx=(keys.has('ArrowRight')||keys.has('KeyD')?1:0)-(keys.has('ArrowLeft')||keys.has('KeyA')?1:0),dz=(keys.has('ArrowDown')||keys.has('KeyS')?1:0)-(keys.has('ArrowUp')||keys.has('KeyW')?1:0);if(clickTarget){dx=clickTarget.x-player.position.x;dz=clickTarget.z-player.position.z;if(Math.hypot(dx,dz)<.3){clickTarget=null;dx=dz=0;}}else{const px=dx;dx=px*Math.cos(yaw)+dz*Math.sin(yaw);dz=-px*Math.sin(yaw)+dz*Math.cos(yaw);}const length=Math.hypot(dx,dz);if(length){dx/=length;dz/=length;const speed=6.4*dt;if(!blocked(player.position.x+dx*speed,player.position.z))player.position.x+=dx*speed;if(!blocked(player.position.x,player.position.z+dz*speed))player.position.z+=dz*speed;player.rotation.y=Math.atan2(dx,dz);}
rollCharacter.update(elapsed,length?6.4:0,0,false);
velocityY-=19*dt;player.position.y+=velocityY*dt;let floor=0;for(const b of obstacles)if(Math.abs(player.position.x-b.x)<b.w&&Math.abs(player.position.z-b.z)<b.d&&player.position.y>=b.h-.3&&velocityY<=0)floor=Math.max(floor,b.h);if(player.position.y<=floor){player.position.y=floor;velocityY=0;grounded=true;}shadow.position.set(player.position.x,.09,player.position.z);shadow.scale.setScalar(Math.max(.4,1-player.position.y*.09));if(Math.abs(player.position.x)>32||Math.abs(player.position.z)>32)respawn();
for(let i=checkpoint+1;i<checkpoints.length;i++)if(player.position.distanceTo(checkpoints[i])<2){checkpoint=i;energy=Math.min(100,energy+15);flash(`Checkpoint ${i+1}. Your progress is safe.`);}
for(const p of pickups){if(p.taken)continue;p.item.rotation.y+=dt;p.item.position.y=1.1+Math.sin(elapsed*2+p.position.x)*.17;if(player.position.clone().add(new T.Vector3(0,.8,0)).distanceTo(p.item.position)<1.4){p.taken=true;p.item.visible=false;collected++;energy=Math.min(100,energy+8);if(collected===1)flash('First spark! Follow the gold trail.');}}
if(player.position.distanceTo(rocket.position)<3.2){if(collected>=8)finish(true);else flash(`Find ${8-collected} more sparks to wake the rocket.`);}if(energy<=0)finish(false);if(elapsed>guideUntil&&guideUntil){$('guide').textContent='Follow the gold trail · Jump the crates · Collect at least 8 sparks';guideUntil=0;}
wind.rotation.z+=dt*.35;ferris.rotation.z=Math.sin(elapsed*.15)*.15;plane.position.set(Math.cos(elapsed*.13)*24,16+Math.sin(elapsed*.2),Math.sin(elapsed*.13)*24);plane.rotation.y=-elapsed*.13;flame.scale.y=.8+Math.sin(elapsed*9)*.18;for(let i=0;i<trail.length;i++)trail[i].material.emissiveIntensity=.45+Math.sin(elapsed*2-i*.2)*.25;
}
$('sparks').textContent=`${collected} / 12 sparks`;$('checkpoint').textContent=`Checkpoint ${checkpoint+1} / 4`;$('energy').value=energy;$('energy-text').textContent=`City light ${Math.ceil(energy)}%`;
target.copy(player.position).add(new T.Vector3(0,1.1,0));desired.copy(player.position).add(new T.Vector3(Math.sin(yaw)*11,8.5,Math.cos(yaw)*11));camera.position.lerp(desired,1-Math.exp(-dt*5));camera.lookAt(target);renderer.render(scene,camera);
}
canvas.tabIndex=0;requestAnimationFrame(frame);
// Read-only diagnostic snapshot for QA and future scene integration.
window.cityRunState=()=>({player:player.position.toArray(),checkpoint,collected,energy,paused,ended,objects:scene.children.length,routeLength:total});
